# Generated by Django 5.0.2 on 2024-07-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='numero_exterior',
            field=models.CharField(help_text='Numero exterior', max_length=15),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='numero_interior',
            field=models.CharField(blank=True, help_text='Numero interior', max_length=15, null=True),
        ),
    ]
